### ISSUE TITLE
 'net_markguerra_android_glwallpapertest' is missing required source folder: 'GLWallpaperService_src'	net_markguerra_android_glwallpapertest		Build path	Build Path Problem 

### ISSUE THREAD

**Issue by Nyceane** [markfguerra/GLWallpaperService#8] opened 2011-01-21 02:25 UTC
This is just after import =/

Description Resource    Path    Location    Type
Project 'net_markguerra_android_glwallpapertest' is missing required source folder: 'GLWallpaperService_src'    net_markguerra_android_glwallpapertest      Build path  Build Path Problem

**Comment by Nyceane** [comment] 2011-01-21 02:38
fixed it

**Comment by markfguerra** [comment] 2011-01-21 02:45
Glad you fixed it. For future visitors, please confirm that this is what resolved your issue:

1- Update Android SDK and Eclipse plugin to the latest version (ADT 0.9.8 or higher)
2- Make sure you have the latest code from the master branch (or any commit up to and including b714a66c344)

This issue was caused by an upgrade to the android developer tools in how it handles Library projects. The change is described here:
http://developer.android.com/guide/developing/eclipse-adt.html#libraryMigrating

FYI The migration procedure described at the link was already done and committed at b714a66c344, so no one should worry about trying to do so themselves.

**Closed as completed** 2011-01-25 17:09 UTC
